services:
  nginx:
    environment:
      MAIN_FILE_CONF: "default-prod.conf"

    ports:
      - "443:443"

  fastapi-core:
    build:
      dockerfile: Dockerfile.prod

  strapi:
    build:
      dockerfile: Dockerfile.prod

  telethon-kspr:
    environment:
      TG_SESSION_FILE_NAME: "profile"