services:
  nginx:
    build: nginx
    container_name: "nginx"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - fastapi-core

  fastapi-core:
    build: fastapi-core
    container_name: "fastapi-core"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - redis-server

  db:
    build: db
    container_name: "db"
    tty: true
    stdin_open: true
    restart: unless-stopped
    shm_size: 128mb

    environment:
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "vHkSbSY&526_*22a"

    volumes:
      - db:/var/lib/postgresql/data

  telethon-kspr:
    build: telethon-kspr
    container_name: "telethon-kspr"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - fastapi-core

  redis-server:
    image: redis/redis-stack-server:7.4.0-v2
    container_name: "redis-server"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - db

  ex-apis:
    build: ex-apis
    container_name: "ex-apis"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - fastapi-core

volumes:
  db: