services:
  nginx:
    build: nginx
    container_name: "nginx"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - fastapi-core

    ports:
      - "127.0.0.1:80:80"

  fastapi-core:
    build: fastapi-core
    container_name: "fastapi-core"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - db

  db:
    build: db
    container_name: "db"
    tty: true
    stdin_open: true
    restart: unless-stopped
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: vHkSbSY&526_*22a

    volumes:
      - db:/var/lib/postgresql/data

  telethon-kspr:
    build: telethon-kspr
    container_name: "telethon-kspr"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - db

volumes:
  db: