services:
  nginx:
    volumes:
      - type: bind
        source: nginx/html
        target: /usr/share/nginx/html

      - type: bind
        source: nginx/conf
        target: /etc/nginx

    environment:
      MAIN_FILE_CONF: "default.conf"

    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:5173:5173"

  fastapi-core:
    build:
      dockerfile: Dockerfile.dev

    volumes:
      - type: bind
        source: fastapi-core/app
        target: /root/app

  telethon-kspr:
    volumes:
      - type: bind
        source: telethon-kspr/app
        target: /root/app

    environment:
      TG_SESSION_FILE_NAME: "profile-dev"

  redis-insight:
    image: redis/redisinsight:2.64
    container_name: "redis-insight"
    tty: true
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - redis-server

    ports:
      - "127.0.0.1:5540:5540"

  ex-apis:
    volumes:
      - type: bind
        source: ex-apis/app
        target: /root/app

  strapi:
    build:
      dockerfile: Dockerfile.dev

    volumes:
      - type: bind
        source: strapi/app
        target: /root/strapi/app