FROM python:3.12.8

WORKDIR /root/app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

RUN apt update && apt upgrade -y

COPY app .
RUN rm requirements.txt

CMD ["fastapi", "run", "main.py", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]