FROM node:18-alpine3.21

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /root/strapi
COPY app/package.json app/package-lock.json .
RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install
ENV PATH=/root/strapi/node_modules/.bin:$PATH

WORKDIR /root/strapi/app

CMD ["strapi", "develop"]